
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mysql://localhost:3306/greendb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: green
      password: green1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  output: 
    ansi:
      enabled: always